# Generated by Django 2.2.5 on 2019-10-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('episodes', models.ManyToManyField(to='mana.Episode')),
                ('manas', models.ManyToManyField(to='mana.Mana')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
