# Generated by Django 2.2.5 on 2019-09-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episode', '0001_initial'),
        ('user', '0002_auto_20190927_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='episodes',
            field=models.ManyToManyField(to='episode.Episode'),
        ),
    ]
