# Generated by Django 2.2.5 on 2019-10-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('link', models.URLField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('link', models.URLField()),
                ('status', models.CharField(choices=[('X', 'Not downloaded'), ('!', 'Downloading'), ('O', 'Downloaded')], default='X', max_length=1)),
                ('mana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mana.Mana')),
            ],
        ),
    ]
