# Generated by Django 2.2.5 on 2019-09-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mana',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
