# Generated by Django 2.2.5 on 2019-09-27 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mana', '0002_auto_20190927_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('X', 'Not downloaded'), ('!', 'Downloading'), ('O', 'Downloaded')], default='X', max_length=1)),
                ('mana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mana.Mana')),
            ],
        ),
    ]
